### PR TITLE
RU Translation

### PR DESCRIPTION
**Pull request by Crabanutij**
Ukranian translation later.

### CODE REVIEW

**Comment by rbasamoyai** [comment]
`ru.json` should be `ru_ru.json` IIRC, also it should be in `src/main/resources/` and not in `src/generated/resources` (refer to `Translators-README.md`. With regards to the UA translation: will this PR have UA loc or will it be in a separate PR?

**Review by rbasamoyai — CHANGES_REQUESTED** [review]
Rename to `ru_ru.json` and move to `src/main/resources/assets/createbigcannons/lang`.

**Comment by rbasamoyai** [comment]
Update: some new entries need adding. Also, there's a change with squibRatio.goggles. Lots of content is being added so expect more

**Comment by Crabanutij** [comment]
I'm going to add new PR with both translations.

**Pull request closed without merging**
