### PR TITLE
Block Hardness Tooltip for all BlockItems

### PR DESCRIPTION
**Pull request by TechTastic**
This PR is for adding a tooltip to all BlockItems to show the hardness of the associated Block if the player is holding shift

The tooltip is added bt a new method added to CBCTooltip and a Mixin into BlockItem.appendHoverText()

There is also a new associated lang key added to datagen of "block.createbigcannons.hardness.tooltip"

### CODE REVIEW

**Comment by TechTastic** [comment]
Bump

**Review by realRobotix — APPROVED** [review]

**Review by realRobotix — APPROVED** [review]

**Comment by rbasamoyai** [comment]
Tooltip events already exist, can use those instead of mixins

**Comment by TechTastic** [comment]
> Tooltip events already exist, can use those instead of mixins

Hmm, I cannot seem to find such an event. The closest I've found is HoverEvent which needs to be added to a Style that's appended to a Component, used in Create for hovering over certain chat messages.

**Comment by rbasamoyai** [comment]
After further thought on this, with the (slightly) new system of hardness that allows for variation depending on block, this would probably not be the most informative. Also, not too much of a fan of displaying this info in this format.

**Pull request closed without merging**
