### PR TITLE
Polish

### PR DESCRIPTION
**Pull request by Abrams11IsBack**
_polish my balls_

### CODE REVIEW

**Comment by rbasamoyai** [comment]
no way 😮

**Comment by rbasamoyai** [comment]
Interesting translation for gunmetal, although perhaps suggest some kind of steel mix instead? dunno, I too don't really know how to approach naming gunmetal

**Comment by Abrams11IsBack** [comment]
> 

well there is no really good word for gunmetal, if you look in the dictionary we call it bronze or "spiż" which is an type of bronze

**Comment by Abrams11IsBack** [comment]
https://www.diki.pl/slownik-angielskiego?q=gunmetal

**Comment by rbasamoyai** [comment]
sounds decent enough then

**Comment by Abrams11IsBack** [comment]
we can always go for netherite but that would be out of context a bit

**Comment by rbasamoyai** [comment]
yeah, i didnt want to suggest an all-netherite construction

**Comment by rbasamoyai** [comment]
"Nethersteel" just sounds like a ripoff but if that suggests alloying properties more I'm all for it

**Pull request merged**
