### PR TITLE
Update and rename en_us.json to pl.json (aka add pl translation)

### PR DESCRIPTION
**Pull request by Kag-ari**
This work of art was created by me and Mlody_02

### CODE REVIEW

**Comment by rbasamoyai** [comment]
There is currently a `pl_pl.json` courtesy of Abrams11IsBack. If you'd like to improve on the translation there, please read the Translator's README.

**Comment by JukoiDev** [comment]
NO CIEBIE KURWA JEGO PIERDZIELONA MAĆ POGIEŁO?

**Comment by JukoiDev** [comment]
TAK JAK H W HISZPAŃSKIM JEST NIE ME, TAK W POLSCE NIE DAJE SIĘ NIENADZOROWANEGO DOSTĘPU DZIECIOM DO INTERNETU

**Comment by rbasamoyai** [comment]
*Don't touch, just look*

**Pull request closed without merging**
